//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace GameConfig.Battle
{ 

public sealed partial class BuffTriggleState :  Bright.Config.BeanBase 
{
    public BuffTriggleState(JSONNode _json) 
    {
        { if(!_json["StateID"].IsNumber) { throw new SerializationException(); }  StateID = (Battle.BuffStateID)_json["StateID"].AsInt; }
        { if(!_json["StateParam"].IsNumber) { throw new SerializationException(); }  StateParam = _json["StateParam"]; }
        PostInit();
    }

    public BuffTriggleState(Battle.BuffStateID StateID, float StateParam ) 
    {
        this.StateID = StateID;
        this.StateParam = StateParam;
        PostInit();
    }

    public static BuffTriggleState DeserializeBuffTriggleState(JSONNode _json)
    {
        return new Battle.BuffTriggleState(_json);
    }

    public Battle.BuffStateID StateID { get; private set; }
    public float StateParam { get; private set; }

    public const int __ID__ = 1328146134;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "StateID:" + StateID + ","
        + "StateParam:" + StateParam + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
