//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameConfig.Battle
{ 
    public enum BuffTimeType
    {
        /// <summary>
        /// 指定持续时间
        /// </summary>
        BUFF_TIME_DURING = 0,
        /// <summary>
        /// 无尽时间
        /// </summary>
        BUFF_TIME_INFINIT = 1,
    }

} 
