//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.Battle
{
public sealed partial class BuffAttrConfig :  Bright.Config.BeanBase 
{
    public BuffAttrConfig(ByteBuf _buf) 
    {
        BuffID = _buf.ReadInt();
        Name = _buf.ReadString();
        StackNum = _buf.ReadInt();
        DurTime = _buf.ReadFloat();
        ResultType = (Battle.BuffResultType)_buf.ReadInt();
        RemoveWhenDie = _buf.ReadInt();
        DotDamageData = Battle.SkillAttrDamageData.DeserializeSkillAttrDamageData(_buf);
        DotTickConfig = Battle.BuffDotTickConfig.DeserializeBuffDotTickConfig(_buf);
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AttrData = new System.Collections.Generic.List<Battle.ResAttrImpactData>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Battle.ResAttrImpactData _e0;  _e0 = Battle.ResAttrImpactData.DeserializeResAttrImpactData(_buf); AttrData.Add(_e0);}}
        PostInit();
    }

    public static BuffAttrConfig DeserializeBuffAttrConfig(ByteBuf _buf)
    {
        return new Battle.BuffAttrConfig(_buf);
    }

    /// <summary>
    /// BuffID
    /// </summary>
    public int BuffID { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 叠加次数
    /// </summary>
    public int StackNum { get; private set; }
    /// <summary>
    /// 持续时间
    /// </summary>
    public float DurTime { get; private set; }
    /// <summary>
    /// 数值效果类型
    /// </summary>
    public Battle.BuffResultType ResultType { get; private set; }
    /// <summary>
    /// 死亡消失
    /// </summary>
    public int RemoveWhenDie { get; private set; }
    public Battle.SkillAttrDamageData DotDamageData { get; private set; }
    public Battle.BuffDotTickConfig DotTickConfig { get; private set; }
    public System.Collections.Generic.List<Battle.ResAttrImpactData> AttrData { get; private set; }

    public const int __ID__ = 1652935996;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        DotDamageData?.Resolve(_tables);
        DotTickConfig?.Resolve(_tables);
        foreach(var _e in AttrData) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        DotDamageData?.TranslateText(translator);
        DotTickConfig?.TranslateText(translator);
        foreach(var _e in AttrData) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "BuffID:" + BuffID + ","
        + "Name:" + Name + ","
        + "StackNum:" + StackNum + ","
        + "DurTime:" + DurTime + ","
        + "ResultType:" + ResultType + ","
        + "RemoveWhenDie:" + RemoveWhenDie + ","
        + "DotDamageData:" + DotDamageData + ","
        + "DotTickConfig:" + DotTickConfig + ","
        + "AttrData:" + Bright.Common.StringUtil.CollectionToString(AttrData) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}