//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameConfig.Battle
{ 
    public enum BuffStateID
    {
        /// <summary>
        /// 无状态
        /// </summary>
        BUFF_STATE_NONE = 0,
        /// <summary>
        /// 眩晕状态
        /// </summary>
        BUFF_STATE_STUN = 1,
        /// <summary>
        /// 无敌状态
        /// </summary>
        BUFF_STATE_UNDEAD = 2,
        /// <summary>
        /// 隐身状态
        /// </summary>
        BUFF_STATE_INVISIBLE = 3,
        /// <summary>
        /// 体形变大
        /// </summary>
        BUFF_STATE_BIGGER = 4,
        /// <summary>
        /// 定身,不能移动
        /// </summary>
        BUFF_STATE_NO_MOVE = 5,
        /// <summary>
        /// 沉默，不能放技能
        /// </summary>
        BUFF_STATE_NO_SKILL = 6,
        /// <summary>
        /// 昏睡
        /// </summary>
        BUFF_STATE_SLEEP = 7,
        /// <summary>
        /// 强制开启阻挡
        /// </summary>
        BUFF_STATE_FORCE_COLLIDER = 8,
        /// <summary>
        /// 无视阻挡
        /// </summary>
        BUFF_STATE_IGNORE_COLLIDER = 9,
        /// <summary>
        /// 最大状态
        /// </summary>
        BUFF_STATE_MAX = 10,
    }

} 
