//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace GameConfig.Battle
{ 

public sealed partial class ResAttrImpactData :  Bright.Config.BeanBase 
{
    public ResAttrImpactData(JSONNode _json) 
    {
        { if(!_json["DataType"].IsNumber) { throw new SerializationException(); }  DataType = (Battle.ActorAttrDataType)_json["DataType"].AsInt; }
        { if(!_json["AddType"].IsNumber) { throw new SerializationException(); }  AddType = (Battle.ActorAttrAddType)_json["AddType"].AsInt; }
        { if(!_json["Value"].IsNumber) { throw new SerializationException(); }  Value = _json["Value"]; }
        PostInit();
    }

    public ResAttrImpactData(Battle.ActorAttrDataType DataType, Battle.ActorAttrAddType AddType, float Value ) 
    {
        this.DataType = DataType;
        this.AddType = AddType;
        this.Value = Value;
        PostInit();
    }

    public static ResAttrImpactData DeserializeResAttrImpactData(JSONNode _json)
    {
        return new Battle.ResAttrImpactData(_json);
    }

    public Battle.ActorAttrDataType DataType { get; private set; }
    public Battle.ActorAttrAddType AddType { get; private set; }
    public float Value { get; private set; }

    public const int __ID__ = 1319292907;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "DataType:" + DataType + ","
        + "AddType:" + AddType + ","
        + "Value:" + Value + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
