//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameConfig.Battle
{ 
    public enum ActorAttrDataType
    {
        /// <summary>
        /// 无效数据
        /// </summary>
        None = 0,
        /// <summary>
        /// 最大血量
        /// </summary>
        MaxHp = 1,
        /// <summary>
        /// 攻击力
        /// </summary>
        Attack = 2,
        /// <summary>
        /// 物理伤害
        /// </summary>
        PhyDamage = 3,
        /// <summary>
        /// 物理防御
        /// </summary>
        PhyDef = 4,
        /// <summary>
        /// 法术伤害
        /// </summary>
        MagicDamage = 5,
        /// <summary>
        /// 法术防御
        /// </summary>
        MagicDef = 6,
        /// <summary>
        /// 移动速度
        /// </summary>
        MoveSpeed = 7,
        /// <summary>
        /// 攻击速度
        /// </summary>
        AttackSpeed = 8,
        /// <summary>
        /// 命中率
        /// </summary>
        Hit = 9,
        /// <summary>
        /// 闪避率
        /// </summary>
        Dodge = 10,
        /// <summary>
        /// 暴击率
        /// </summary>
        CriticalAtkRatio = 11,
        /// <summary>
        /// San值(疯狂值)
        /// </summary>
        SanValue = 12,
        /// <summary>
        /// 最大MP
        /// </summary>
        MaxMp = 13,
        /// <summary>
        /// 物理伤害倍率
        /// </summary>
        PhyDamageRatio = 14,
        /// <summary>
        /// 魔法伤害倍率
        /// </summary>
        MagicDamageRatio = 15,
        /// <summary>
        /// 暴击倍率
        /// </summary>
        CriticalRatio = 16,
        /// <summary>
        /// 暴击减免
        /// </summary>
        CriticalReduce = 17,
    }

} 
