//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameConfig.Battle
{ 
    public enum ActorAttrAddType
    {
        /// <summary>
        /// 无效数据
        /// </summary>
        NONE = 0,
        /// <summary>
        /// 加法计算
        /// </summary>
        ABSOLUTE_VAL = 1,
        /// <summary>
        /// 多个项结果累加，然后对加法做乘法
        /// </summary>
        SUM_PERCENT_VAL = 2,
        /// <summary>
        /// 每一项都是对最终结果做乘法
        /// </summary>
        MUL_PERCENT_VAL = 3,
    }

} 
