//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameConfig.Battle
{ 
    public enum BuffResultType
    {
        /// <summary>
        /// 无
        /// </summary>
        BUFF_RESULT_NONE = 0,
        /// <summary>
        /// 物理攻击提升
        /// </summary>
        BUFF_RESULT_PHY_ATK_UP = 1,
        /// <summary>
        /// 物理攻击降低
        /// </summary>
        BUFF_RESULT_PHY_ATK_DOWN = 2,
        /// <summary>
        /// 物理防御提升
        /// </summary>
        BUFF_RESULT_PHY_DEF_UP = 3,
        /// <summary>
        /// 物理防御降低
        /// </summary>
        BUFF_RESULT_PHY_DEF_DOWN = 4,
        /// <summary>
        /// 物理命中提升
        /// </summary>
        BUFF_RESULT_PHY_HIT_UP = 5,
        /// <summary>
        /// 物理命中降低
        /// </summary>
        BUFF_RESULT_PHY_HIT_DOWN = 6,
        /// <summary>
        /// 物理持续掉血
        /// </summary>
        BUFF_RESULT_PHY_LOSE_HP = 7,
        /// <summary>
        /// 法术攻击提升
        /// </summary>
        BUFF_RESULT_MAG_ATK_UP = 8,
        /// <summary>
        /// 法术攻击降低
        /// </summary>
        BUFF_RESULT_MAG_ATK_DOWN = 9,
        /// <summary>
        /// 法术防御提升
        /// </summary>
        BUFF_RESULT_MAG_DEF_UP = 10,
        /// <summary>
        /// 法术防御降低
        /// </summary>
        BUFF_RESULT_MAG_DEF_DOWN = 11,
        /// <summary>
        /// 法术命中提升
        /// </summary>
        BUFF_RESULT_MAG_HIT_UP = 12,
        /// <summary>
        /// 法术命中降低
        /// </summary>
        BUFF_RESULT_MAG_HIT_DOWN = 13,
        /// <summary>
        /// 法术持续掉血
        /// </summary>
        BUFF_RESULT_MAG_LOSE_HP = 14,
        /// <summary>
        /// 暴击率提升
        /// </summary>
        BUFF_RESULT_CIRT_UP = 15,
        /// <summary>
        /// 暴击率降低
        /// </summary>
        BUFF_RESULT_CIRT_DOWN = 16,
        /// <summary>
        /// 暴击倍率提升
        /// </summary>
        BUFF_RESULT_CIRT_VALUE_UP = 17,
        /// <summary>
        /// 暴击倍率降低
        /// </summary>
        BUFF_RESULT_CIRT_VALUE_DOWN = 18,
        /// <summary>
        /// 移速提升
        /// </summary>
        BUFF_RESULT_MOVE_SPEED_UP = 19,
        /// <summary>
        /// 移速降低
        /// </summary>
        BUFF_RESULT_MOVE_SPEED_DOWN = 20,
    }

} 
