//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameConfig.Battle
{ 
    public enum BuffReplaceType
    {
        /// <summary>
        /// 更新时间范围
        /// </summary>
        BUFF_REPLACE_INSTEAD = 0,
        /// <summary>
        /// 不允许叠加
        /// </summary>
        BUFF_REPLACE_FORBIT = 1,
        /// <summary>
        /// 累加时间范围
        /// </summary>
        BUFF_REPLACE_ADD_TIME = 2,
        /// <summary>
        /// 叠加数值
        /// </summary>
        BUFF_REPLACE_ADD_ATTR = 3,
        /// <summary>
        /// 叠加种类
        /// </summary>
        BUFF_REPLACE_TYPE_COUNT = 4,
    }

} 
