//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.Battle
{
public sealed partial class BuffConfig :  Bright.Config.BeanBase 
{
    public BuffConfig(ByteBuf _buf) 
    {
        BuffID = _buf.ReadInt();
        Name = _buf.ReadString();
        PrefId = _buf.ReadInt();
        TimeType = (Battle.BuffTimeType)_buf.ReadInt();
        ReplaceType = (Battle.BuffReplaceType)_buf.ReadInt();
        State = Battle.BuffTriggleState.DeserializeBuffTriggleState(_buf);
        PostInit();
    }

    public static BuffConfig DeserializeBuffConfig(ByteBuf _buf)
    {
        return new Battle.BuffConfig(_buf);
    }

    /// <summary>
    /// BuffID
    /// </summary>
    public int BuffID { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 表现ID
    /// </summary>
    public int PrefId { get; private set; }
    /// <summary>
    /// 持续类型
    /// </summary>
    public Battle.BuffTimeType TimeType { get; private set; }
    /// <summary>
    /// 叠加类型
    /// </summary>
    public Battle.BuffReplaceType ReplaceType { get; private set; }
    public Battle.BuffTriggleState State { get; private set; }

    public const int __ID__ = 1807662187;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        State?.Resolve(_tables);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        State?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "BuffID:" + BuffID + ","
        + "Name:" + Name + ","
        + "PrefId:" + PrefId + ","
        + "TimeType:" + TimeType + ","
        + "ReplaceType:" + ReplaceType + ","
        + "State:" + State + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}