//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.Battle
{
public sealed partial class ResAttrImpactData :  Bright.Config.BeanBase 
{
    public ResAttrImpactData(ByteBuf _buf) 
    {
        DataType = (Battle.ActorAttrDataType)_buf.ReadInt();
        AddType = (Battle.ActorAttrAddType)_buf.ReadInt();
        Value = _buf.ReadFloat();
        PostInit();
    }

    public static ResAttrImpactData DeserializeResAttrImpactData(ByteBuf _buf)
    {
        return new Battle.ResAttrImpactData(_buf);
    }

    public Battle.ActorAttrDataType DataType { get; private set; }
    public Battle.ActorAttrAddType AddType { get; private set; }
    public float Value { get; private set; }

    public const int __ID__ = 1319292907;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "DataType:" + DataType + ","
        + "AddType:" + AddType + ","
        + "Value:" + Value + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}