//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameConfig.Battle
{ 
    public enum SkillAttrDamageType
    {
        /// <summary>
        /// 无数值
        /// </summary>
        ATTR_TYPE_NONE = 0,
        /// <summary>
        /// 按释放者的伤害类型*X%+固定值计算,目标有防御计算
        /// </summary>
        ATTR_TYPE_DMG_WEAPON = 1,
        /// <summary>
        /// 按释放者的伤害类型*X%+固定值计算（无视目标的防御）
        /// </summary>
        ATTR_TYPE_DMG_NO_DEFEND = 2,
        /// <summary>
        /// 按受击者的气血上限*X%+固定值计算（无视目标的防御）
        /// </summary>
        ATTR_TYPE_DMG_TARGET_HP_NO_DEFEND = 3,
        /// <summary>
        /// 按释放者的攻击类型*X%+固定值计算，恢复当前生命
        /// </summary>
        ATTR_TYPE_HP_AS_ATK = 4,
        /// <summary>
        /// 按受击者的HP上限*X%+固定值计算，恢复当前生命
        /// </summary>
        ATTR_TYPE_HP_RATIO = 5,
    }

} 
