// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto_cs_player.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GameProto {

  /// <summary>Holder for reflection information generated from proto_cs_player.proto</summary>
  public static partial class ProtoCsPlayerReflection {

    #region Descriptor
    /// <summary>File descriptor for proto_cs_player.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoCsPlayerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVwcm90b19jc19wbGF5ZXIucHJvdG8SCUdhbWVQcm90bxoVcHJvdG9fY3Nf",
            "Y29tbW9uLnByb3RvIlIKDUNTQWN0TG9naW5SZXESCwoDVWluGAEgASgNEg0K",
            "BVN2cklEGAIgASgNEhAKCEF1dGhUaW1lGAMgASgNEhMKC05ldHdvcmtUeXBl",
            "GAQgASgNIlQKDUNTQWN0TG9naW5SZXMSJgoGUmVzdWx0GAEgASgLMhYuR2Ft",
            "ZVByb3RvLlByb3RvUmVzdWx0EgsKA1VpbhgCIAEoDRIOCgZSb2xlSUQYAyAB",
            "KA1QAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::GameProto.ProtoCsCommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProto.CSActLoginReq), global::GameProto.CSActLoginReq.Parser, new[]{ "Uin", "SvrID", "AuthTime", "NetworkType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProto.CSActLoginRes), global::GameProto.CSActLoginRes.Parser, new[]{ "Result", "Uin", "RoleID" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 角色登录结果请求
  /// </summary>
  public sealed partial class CSActLoginReq : pb::IMessage<CSActLoginReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CSActLoginReq> _parser = new pb::MessageParser<CSActLoginReq>(() => new CSActLoginReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CSActLoginReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProto.ProtoCsPlayerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CSActLoginReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CSActLoginReq(CSActLoginReq other) : this() {
      uin_ = other.uin_;
      svrID_ = other.svrID_;
      authTime_ = other.authTime_;
      networkType_ = other.networkType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CSActLoginReq Clone() {
      return new CSActLoginReq(this);
    }

    /// <summary>Field number for the "Uin" field.</summary>
    public const int UinFieldNumber = 1;
    private uint uin_;
    /// <summary>
    ///帐号Uin
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Uin {
      get { return uin_; }
      set {
        uin_ = value;
      }
    }

    /// <summary>Field number for the "SvrID" field.</summary>
    public const int SvrIDFieldNumber = 2;
    private uint svrID_;
    /// <summary>
    ///服务器ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SvrID {
      get { return svrID_; }
      set {
        svrID_ = value;
      }
    }

    /// <summary>Field number for the "AuthTime" field.</summary>
    public const int AuthTimeFieldNumber = 3;
    private uint authTime_;
    /// <summary>
    ///账户认证的时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AuthTime {
      get { return authTime_; }
      set {
        authTime_ = value;
      }
    }

    /// <summary>Field number for the "NetworkType" field.</summary>
    public const int NetworkTypeFieldNumber = 4;
    private uint networkType_;
    /// <summary>
    ///网络类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NetworkType {
      get { return networkType_; }
      set {
        networkType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CSActLoginReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CSActLoginReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Uin != other.Uin) return false;
      if (SvrID != other.SvrID) return false;
      if (AuthTime != other.AuthTime) return false;
      if (NetworkType != other.NetworkType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Uin != 0) hash ^= Uin.GetHashCode();
      if (SvrID != 0) hash ^= SvrID.GetHashCode();
      if (AuthTime != 0) hash ^= AuthTime.GetHashCode();
      if (NetworkType != 0) hash ^= NetworkType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Uin != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Uin);
      }
      if (SvrID != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(SvrID);
      }
      if (AuthTime != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(AuthTime);
      }
      if (NetworkType != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(NetworkType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Uin != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Uin);
      }
      if (SvrID != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(SvrID);
      }
      if (AuthTime != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(AuthTime);
      }
      if (NetworkType != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(NetworkType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Uin != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Uin);
      }
      if (SvrID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SvrID);
      }
      if (AuthTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AuthTime);
      }
      if (NetworkType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NetworkType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CSActLoginReq other) {
      if (other == null) {
        return;
      }
      if (other.Uin != 0) {
        Uin = other.Uin;
      }
      if (other.SvrID != 0) {
        SvrID = other.SvrID;
      }
      if (other.AuthTime != 0) {
        AuthTime = other.AuthTime;
      }
      if (other.NetworkType != 0) {
        NetworkType = other.NetworkType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Uin = input.ReadUInt32();
            break;
          }
          case 16: {
            SvrID = input.ReadUInt32();
            break;
          }
          case 24: {
            AuthTime = input.ReadUInt32();
            break;
          }
          case 32: {
            NetworkType = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Uin = input.ReadUInt32();
            break;
          }
          case 16: {
            SvrID = input.ReadUInt32();
            break;
          }
          case 24: {
            AuthTime = input.ReadUInt32();
            break;
          }
          case 32: {
            NetworkType = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 角色登录结果返回
  /// </summary>
  public sealed partial class CSActLoginRes : pb::IMessage<CSActLoginRes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CSActLoginRes> _parser = new pb::MessageParser<CSActLoginRes>(() => new CSActLoginRes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CSActLoginRes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProto.ProtoCsPlayerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CSActLoginRes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CSActLoginRes(CSActLoginRes other) : this() {
      result_ = other.result_ != null ? other.result_.Clone() : null;
      uin_ = other.uin_;
      roleID_ = other.roleID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CSActLoginRes Clone() {
      return new CSActLoginRes(this);
    }

    /// <summary>Field number for the "Result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::GameProto.ProtoResult result_;
    /// <summary>
    ///返回操作结果
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.ProtoResult Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "Uin" field.</summary>
    public const int UinFieldNumber = 2;
    private uint uin_;
    /// <summary>
    ///帐号Uin
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Uin {
      get { return uin_; }
      set {
        uin_ = value;
      }
    }

    /// <summary>Field number for the "RoleID" field.</summary>
    public const int RoleIDFieldNumber = 3;
    private uint roleID_;
    /// <summary>
    ///角色ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RoleID {
      get { return roleID_; }
      set {
        roleID_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CSActLoginRes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CSActLoginRes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Result, other.Result)) return false;
      if (Uin != other.Uin) return false;
      if (RoleID != other.RoleID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (result_ != null) hash ^= Result.GetHashCode();
      if (Uin != 0) hash ^= Uin.GetHashCode();
      if (RoleID != 0) hash ^= RoleID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (result_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Result);
      }
      if (Uin != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Uin);
      }
      if (RoleID != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(RoleID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (result_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Result);
      }
      if (Uin != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Uin);
      }
      if (RoleID != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(RoleID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (result_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Result);
      }
      if (Uin != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Uin);
      }
      if (RoleID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RoleID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CSActLoginRes other) {
      if (other == null) {
        return;
      }
      if (other.result_ != null) {
        if (result_ == null) {
          Result = new global::GameProto.ProtoResult();
        }
        Result.MergeFrom(other.Result);
      }
      if (other.Uin != 0) {
        Uin = other.Uin;
      }
      if (other.RoleID != 0) {
        RoleID = other.RoleID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (result_ == null) {
              Result = new global::GameProto.ProtoResult();
            }
            input.ReadMessage(Result);
            break;
          }
          case 16: {
            Uin = input.ReadUInt32();
            break;
          }
          case 24: {
            RoleID = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (result_ == null) {
              Result = new global::GameProto.ProtoResult();
            }
            input.ReadMessage(Result);
            break;
          }
          case 16: {
            Uin = input.ReadUInt32();
            break;
          }
          case 24: {
            RoleID = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
