//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using ProtoBuf;
using TEngine;
using System.Collections.Generic;

namespace GameProto
{
	// 这个文件只放协议，和协议头
	// 消息协议
	[Serializable,global::ProtoBuf.ProtoContract(Name = @"CSPkg")]
	public partial class CSPkg
	{
		[global::ProtoBuf.ProtoMember(1)]
		public CSPkgHead Head { get; set; }

		[global::ProtoBuf.ProtoMember(2)]
		public CSPkgBody Body { get; set; }

	}

	// 消息协议头
	[Serializable,global::ProtoBuf.ProtoContract(Name = @"CSPkgHead")]
	public partial class CSPkgHead
	{
		[global::ProtoBuf.ProtoMember(1)]
		public uint MsgId { get; set; }

		[global::ProtoBuf.ProtoMember(2)]
		public uint MsgLength { get; set; }

		[global::ProtoBuf.ProtoMember(3)]
		public uint MsgVersion { get; set; }

		[global::ProtoBuf.ProtoMember(4)]
		public uint Echo { get; set; }

		[global::ProtoBuf.ProtoMember(5)]
		public uint SvrTime { get; set; }

	}

	// 消息协议体
	[Serializable,global::ProtoBuf.ProtoContract(Name = @"CSPkgBody")]
	public partial class CSPkgBody
	{
		[global::ProtoBuf.ProtoMember(1)]
		public CSActLoginReq ActLoginReq { get; set; }

		[global::ProtoBuf.ProtoMember(2)]
		public CSActLoginRes ActLoginRes { get; set; }

	}

	// 消息结果
	[Serializable,global::ProtoBuf.ProtoContract(Name = @"ProtoResult")]
	public partial class ProtoResult
	{
		[global::ProtoBuf.ProtoMember(3)]
		public List<string> Params = new List<string>();

	}

	// 协议ID
	[global::ProtoBuf.ProtoContract()]
	public enum CSMsgID
	{
		CS_START		= 0,

		CS_HeartBeat    = 10001,

		CS_END          = 10000,

	}

}
