//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using ProtoBuf;
using TEngine;
using System.Collections.Generic;

namespace GameProto
{
	// 常用协议
	// 消息结果
	[Serializable,global::ProtoBuf.ProtoContract(Name = @"ProtoResult")]
	public partial class ProtoResult
	{
		[global::ProtoBuf.ProtoMember(3)]
		public List<string> Params = new List<string>();

	}

	// 心跳请求
	[Serializable,global::ProtoBuf.ProtoContract(Name = @"CSHeatBeatReq")]
	public partial class CSHeatBeatReq
	{
		[global::ProtoBuf.ProtoMember(1)]
		public float HeatEchoTime { get; set; }

	}

	// 角色登录结果返回
	[Serializable,global::ProtoBuf.ProtoContract(Name = @"CSHeatBeatRes")]
	public partial class CSHeatBeatRes
	{
		[global::ProtoBuf.ProtoMember(1)]
		public float HeatEchoTime { get; set; }

	}

}
