// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto_cs.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GameProto {

  /// <summary>Holder for reflection information generated from proto_cs.proto</summary>
  public static partial class ProtoCsReflection {

    #region Descriptor
    /// <summary>File descriptor for proto_cs.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoCsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5wcm90b19jcy5wcm90bxIJR2FtZVByb3RvGhVwcm90b19jc19jb21tb24u",
            "cHJvdG8aFXByb3RvX2NzX3BsYXllci5wcm90byJPCgVDU1BrZxIiCgRIZWFk",
            "GAEgASgLMhQuR2FtZVByb3RvLkNTUGtnSGVhZBIiCgRCb2R5GAIgASgLMhQu",
            "R2FtZVByb3RvLkNTUGtnQm9keSJgCglDU1BrZ0hlYWQSDQoFTXNnSWQYASAB",
            "KA0SEQoJTXNnTGVuZ3RoGAIgASgNEhIKCk1zZ1ZlcnNpb24YAyABKA0SDAoE",
            "RWNobxgEIAEoDRIPCgdTdnJUaW1lGAUgASgNIscBCglDU1BrZ0JvZHkSLQoL",
            "SGVhdEJlYXRSZXEYASABKAsyGC5HYW1lUHJvdG8uQ1NIZWF0QmVhdFJlcRIt",
            "CgtIZWF0QmVhdFJlcxgCIAEoCzIYLkdhbWVQcm90by5DU0hlYXRCZWF0UmVz",
            "Ei0KC0FjdExvZ2luUmVxGAMgASgLMhguR2FtZVByb3RvLkNTQWN0TG9naW5S",
            "ZXESLQoLQWN0TG9naW5SZXMYBCABKAsyGC5HYW1lUHJvdG8uQ1NBY3RMb2dp",
            "blJlcyqBAQoHQ1NNc2dJRBIMCghDU19TVEFSVBAAEhgKE0NTX0NNRF9IRUFU",
            "QkVBVF9SRVEQ6QcSGAoTQ1NfQ01EX0hFQVRCRUFUX1JFUxDqBxIZChRDU19D",
            "TURfQUNUX0xPR0lOX1JFURDRDxIZChRDU19DTURfQUNUX0xPR0lOX1JFUxDS",
            "D1AAUAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::GameProto.ProtoCsCommonReflection.Descriptor, global::GameProto.ProtoCsPlayerReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GameProto.CSMsgID), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProto.CSPkg), global::GameProto.CSPkg.Parser, new[]{ "Head", "Body" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProto.CSPkgHead), global::GameProto.CSPkgHead.Parser, new[]{ "MsgId", "MsgLength", "MsgVersion", "Echo", "SvrTime" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProto.CSPkgBody), global::GameProto.CSPkgBody.Parser, new[]{ "HeatBeatReq", "HeatBeatRes", "ActLoginReq", "ActLoginRes" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 协议ID
  /// </summary>
  public enum CSMsgID {
    [pbr::OriginalName("CS_START")] CsStart = 0,
    /// <summary>
    ///心跳请求
    /// </summary>
    [pbr::OriginalName("CS_CMD_HEATBEAT_REQ")] CsCmdHeatbeatReq = 1001,
    /// <summary>
    ///心跳回包
    /// </summary>
    [pbr::OriginalName("CS_CMD_HEATBEAT_RES")] CsCmdHeatbeatRes = 1002,
    /// <summary>
    ///帐号登录请求
    /// </summary>
    [pbr::OriginalName("CS_CMD_ACT_LOGIN_REQ")] CsCmdActLoginReq = 2001,
    /// <summary>
    ///帐号登录回包
    /// </summary>
    [pbr::OriginalName("CS_CMD_ACT_LOGIN_RES")] CsCmdActLoginRes = 2002,
  }

  #endregion

  #region Messages
  /// <summary>
  /// 消息协议
  /// </summary>
  public sealed partial class CSPkg : pb::IMessage<CSPkg>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CSPkg> _parser = new pb::MessageParser<CSPkg>(() => new CSPkg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CSPkg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProto.ProtoCsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CSPkg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CSPkg(CSPkg other) : this() {
      head_ = other.head_ != null ? other.head_.Clone() : null;
      body_ = other.body_ != null ? other.body_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CSPkg Clone() {
      return new CSPkg(this);
    }

    /// <summary>Field number for the "Head" field.</summary>
    public const int HeadFieldNumber = 1;
    private global::GameProto.CSPkgHead head_;
    /// <summary>
    ///消息协议头
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.CSPkgHead Head {
      get { return head_; }
      set {
        head_ = value;
      }
    }

    /// <summary>Field number for the "Body" field.</summary>
    public const int BodyFieldNumber = 2;
    private global::GameProto.CSPkgBody body_;
    /// <summary>
    ///消息协议体
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.CSPkgBody Body {
      get { return body_; }
      set {
        body_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CSPkg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CSPkg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Head, other.Head)) return false;
      if (!object.Equals(Body, other.Body)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (head_ != null) hash ^= Head.GetHashCode();
      if (body_ != null) hash ^= Body.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (head_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Head);
      }
      if (body_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Body);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (head_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Head);
      }
      if (body_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Body);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (head_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Head);
      }
      if (body_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Body);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CSPkg other) {
      if (other == null) {
        return;
      }
      if (other.head_ != null) {
        if (head_ == null) {
          Head = new global::GameProto.CSPkgHead();
        }
        Head.MergeFrom(other.Head);
      }
      if (other.body_ != null) {
        if (body_ == null) {
          Body = new global::GameProto.CSPkgBody();
        }
        Body.MergeFrom(other.Body);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (head_ == null) {
              Head = new global::GameProto.CSPkgHead();
            }
            input.ReadMessage(Head);
            break;
          }
          case 18: {
            if (body_ == null) {
              Body = new global::GameProto.CSPkgBody();
            }
            input.ReadMessage(Body);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (head_ == null) {
              Head = new global::GameProto.CSPkgHead();
            }
            input.ReadMessage(Head);
            break;
          }
          case 18: {
            if (body_ == null) {
              Body = new global::GameProto.CSPkgBody();
            }
            input.ReadMessage(Body);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 消息协议头
  /// </summary>
  public sealed partial class CSPkgHead : pb::IMessage<CSPkgHead>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CSPkgHead> _parser = new pb::MessageParser<CSPkgHead>(() => new CSPkgHead());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CSPkgHead> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProto.ProtoCsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CSPkgHead() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CSPkgHead(CSPkgHead other) : this() {
      msgId_ = other.msgId_;
      msgLength_ = other.msgLength_;
      msgVersion_ = other.msgVersion_;
      echo_ = other.echo_;
      svrTime_ = other.svrTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CSPkgHead Clone() {
      return new CSPkgHead(this);
    }

    /// <summary>Field number for the "MsgId" field.</summary>
    public const int MsgIdFieldNumber = 1;
    private uint msgId_;
    /// <summary>
    ///协议号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MsgId {
      get { return msgId_; }
      set {
        msgId_ = value;
      }
    }

    /// <summary>Field number for the "MsgLength" field.</summary>
    public const int MsgLengthFieldNumber = 2;
    private uint msgLength_;
    /// <summary>
    ///协议长度
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MsgLength {
      get { return msgLength_; }
      set {
        msgLength_ = value;
      }
    }

    /// <summary>Field number for the "MsgVersion" field.</summary>
    public const int MsgVersionFieldNumber = 3;
    private uint msgVersion_;
    /// <summary>
    ///协议版本
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MsgVersion {
      get { return msgVersion_; }
      set {
        msgVersion_ = value;
      }
    }

    /// <summary>Field number for the "Echo" field.</summary>
    public const int EchoFieldNumber = 4;
    private uint echo_;
    /// <summary>
    ///回带字段
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Echo {
      get { return echo_; }
      set {
        echo_ = value;
      }
    }

    /// <summary>Field number for the "SvrTime" field.</summary>
    public const int SvrTimeFieldNumber = 5;
    private uint svrTime_;
    /// <summary>
    ///服务器时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SvrTime {
      get { return svrTime_; }
      set {
        svrTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CSPkgHead);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CSPkgHead other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MsgId != other.MsgId) return false;
      if (MsgLength != other.MsgLength) return false;
      if (MsgVersion != other.MsgVersion) return false;
      if (Echo != other.Echo) return false;
      if (SvrTime != other.SvrTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MsgId != 0) hash ^= MsgId.GetHashCode();
      if (MsgLength != 0) hash ^= MsgLength.GetHashCode();
      if (MsgVersion != 0) hash ^= MsgVersion.GetHashCode();
      if (Echo != 0) hash ^= Echo.GetHashCode();
      if (SvrTime != 0) hash ^= SvrTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MsgId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MsgId);
      }
      if (MsgLength != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(MsgLength);
      }
      if (MsgVersion != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(MsgVersion);
      }
      if (Echo != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Echo);
      }
      if (SvrTime != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(SvrTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MsgId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MsgId);
      }
      if (MsgLength != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(MsgLength);
      }
      if (MsgVersion != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(MsgVersion);
      }
      if (Echo != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Echo);
      }
      if (SvrTime != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(SvrTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MsgId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MsgId);
      }
      if (MsgLength != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MsgLength);
      }
      if (MsgVersion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MsgVersion);
      }
      if (Echo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Echo);
      }
      if (SvrTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SvrTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CSPkgHead other) {
      if (other == null) {
        return;
      }
      if (other.MsgId != 0) {
        MsgId = other.MsgId;
      }
      if (other.MsgLength != 0) {
        MsgLength = other.MsgLength;
      }
      if (other.MsgVersion != 0) {
        MsgVersion = other.MsgVersion;
      }
      if (other.Echo != 0) {
        Echo = other.Echo;
      }
      if (other.SvrTime != 0) {
        SvrTime = other.SvrTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MsgId = input.ReadUInt32();
            break;
          }
          case 16: {
            MsgLength = input.ReadUInt32();
            break;
          }
          case 24: {
            MsgVersion = input.ReadUInt32();
            break;
          }
          case 32: {
            Echo = input.ReadUInt32();
            break;
          }
          case 40: {
            SvrTime = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MsgId = input.ReadUInt32();
            break;
          }
          case 16: {
            MsgLength = input.ReadUInt32();
            break;
          }
          case 24: {
            MsgVersion = input.ReadUInt32();
            break;
          }
          case 32: {
            Echo = input.ReadUInt32();
            break;
          }
          case 40: {
            SvrTime = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 消息协议体
  /// </summary>
  public sealed partial class CSPkgBody : pb::IMessage<CSPkgBody>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CSPkgBody> _parser = new pb::MessageParser<CSPkgBody>(() => new CSPkgBody());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CSPkgBody> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProto.ProtoCsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CSPkgBody() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CSPkgBody(CSPkgBody other) : this() {
      heatBeatReq_ = other.heatBeatReq_ != null ? other.heatBeatReq_.Clone() : null;
      heatBeatRes_ = other.heatBeatRes_ != null ? other.heatBeatRes_.Clone() : null;
      actLoginReq_ = other.actLoginReq_ != null ? other.actLoginReq_.Clone() : null;
      actLoginRes_ = other.actLoginRes_ != null ? other.actLoginRes_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CSPkgBody Clone() {
      return new CSPkgBody(this);
    }

    /// <summary>Field number for the "HeatBeatReq" field.</summary>
    public const int HeatBeatReqFieldNumber = 1;
    private global::GameProto.CSHeatBeatReq heatBeatReq_;
    /// <summary>
    ///心跳请求
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.CSHeatBeatReq HeatBeatReq {
      get { return heatBeatReq_; }
      set {
        heatBeatReq_ = value;
      }
    }

    /// <summary>Field number for the "HeatBeatRes" field.</summary>
    public const int HeatBeatResFieldNumber = 2;
    private global::GameProto.CSHeatBeatRes heatBeatRes_;
    /// <summary>
    ///心跳回包
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.CSHeatBeatRes HeatBeatRes {
      get { return heatBeatRes_; }
      set {
        heatBeatRes_ = value;
      }
    }

    /// <summary>Field number for the "ActLoginReq" field.</summary>
    public const int ActLoginReqFieldNumber = 3;
    private global::GameProto.CSActLoginReq actLoginReq_;
    /// <summary>
    ///帐号登录请求
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.CSActLoginReq ActLoginReq {
      get { return actLoginReq_; }
      set {
        actLoginReq_ = value;
      }
    }

    /// <summary>Field number for the "ActLoginRes" field.</summary>
    public const int ActLoginResFieldNumber = 4;
    private global::GameProto.CSActLoginRes actLoginRes_;
    /// <summary>
    ///帐号登录回包
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameProto.CSActLoginRes ActLoginRes {
      get { return actLoginRes_; }
      set {
        actLoginRes_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CSPkgBody);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CSPkgBody other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(HeatBeatReq, other.HeatBeatReq)) return false;
      if (!object.Equals(HeatBeatRes, other.HeatBeatRes)) return false;
      if (!object.Equals(ActLoginReq, other.ActLoginReq)) return false;
      if (!object.Equals(ActLoginRes, other.ActLoginRes)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (heatBeatReq_ != null) hash ^= HeatBeatReq.GetHashCode();
      if (heatBeatRes_ != null) hash ^= HeatBeatRes.GetHashCode();
      if (actLoginReq_ != null) hash ^= ActLoginReq.GetHashCode();
      if (actLoginRes_ != null) hash ^= ActLoginRes.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (heatBeatReq_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(HeatBeatReq);
      }
      if (heatBeatRes_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(HeatBeatRes);
      }
      if (actLoginReq_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ActLoginReq);
      }
      if (actLoginRes_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ActLoginRes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (heatBeatReq_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(HeatBeatReq);
      }
      if (heatBeatRes_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(HeatBeatRes);
      }
      if (actLoginReq_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ActLoginReq);
      }
      if (actLoginRes_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ActLoginRes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (heatBeatReq_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HeatBeatReq);
      }
      if (heatBeatRes_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HeatBeatRes);
      }
      if (actLoginReq_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ActLoginReq);
      }
      if (actLoginRes_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ActLoginRes);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CSPkgBody other) {
      if (other == null) {
        return;
      }
      if (other.heatBeatReq_ != null) {
        if (heatBeatReq_ == null) {
          HeatBeatReq = new global::GameProto.CSHeatBeatReq();
        }
        HeatBeatReq.MergeFrom(other.HeatBeatReq);
      }
      if (other.heatBeatRes_ != null) {
        if (heatBeatRes_ == null) {
          HeatBeatRes = new global::GameProto.CSHeatBeatRes();
        }
        HeatBeatRes.MergeFrom(other.HeatBeatRes);
      }
      if (other.actLoginReq_ != null) {
        if (actLoginReq_ == null) {
          ActLoginReq = new global::GameProto.CSActLoginReq();
        }
        ActLoginReq.MergeFrom(other.ActLoginReq);
      }
      if (other.actLoginRes_ != null) {
        if (actLoginRes_ == null) {
          ActLoginRes = new global::GameProto.CSActLoginRes();
        }
        ActLoginRes.MergeFrom(other.ActLoginRes);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (heatBeatReq_ == null) {
              HeatBeatReq = new global::GameProto.CSHeatBeatReq();
            }
            input.ReadMessage(HeatBeatReq);
            break;
          }
          case 18: {
            if (heatBeatRes_ == null) {
              HeatBeatRes = new global::GameProto.CSHeatBeatRes();
            }
            input.ReadMessage(HeatBeatRes);
            break;
          }
          case 26: {
            if (actLoginReq_ == null) {
              ActLoginReq = new global::GameProto.CSActLoginReq();
            }
            input.ReadMessage(ActLoginReq);
            break;
          }
          case 34: {
            if (actLoginRes_ == null) {
              ActLoginRes = new global::GameProto.CSActLoginRes();
            }
            input.ReadMessage(ActLoginRes);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (heatBeatReq_ == null) {
              HeatBeatReq = new global::GameProto.CSHeatBeatReq();
            }
            input.ReadMessage(HeatBeatReq);
            break;
          }
          case 18: {
            if (heatBeatRes_ == null) {
              HeatBeatRes = new global::GameProto.CSHeatBeatRes();
            }
            input.ReadMessage(HeatBeatRes);
            break;
          }
          case 26: {
            if (actLoginReq_ == null) {
              ActLoginReq = new global::GameProto.CSActLoginReq();
            }
            input.ReadMessage(ActLoginReq);
            break;
          }
          case 34: {
            if (actLoginRes_ == null) {
              ActLoginRes = new global::GameProto.CSActLoginRes();
            }
            input.ReadMessage(ActLoginRes);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
