//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.Battle
{
public sealed partial class BuffDotTickConfig :  Bright.Config.BeanBase 
{
    public BuffDotTickConfig(ByteBuf _buf) 
    {
        TickTime = _buf.ReadFloat();
        TickWhenAdd = _buf.ReadInt();
        PostInit();
    }

    public static BuffDotTickConfig DeserializeBuffDotTickConfig(ByteBuf _buf)
    {
        return new Battle.BuffDotTickConfig(_buf);
    }

    public float TickTime { get; private set; }
    public int TickWhenAdd { get; private set; }

    public const int __ID__ = 2124630047;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "TickTime:" + TickTime + ","
        + "TickWhenAdd:" + TickWhenAdd + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}