//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameConfig.Battle
{ 
    public enum SkillMagicType
    {
        /// <summary>
        /// 无类型
        /// </summary>
        SKILL_TYPE_NONE = 0,
        /// <summary>
        /// 物理伤害属性
        /// </summary>
        SKILL_TYPE_DMG_PHY = 1,
        /// <summary>
        /// 魔法伤害属性
        /// </summary>
        SKILL_TYPE_DMG_MAGIC = 2,
    }

} 
