// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: msg.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Msg
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string msgId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public byte[] msgContent { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
